"""Stage 5.2c — workload profiler integration tests for the compatible-island method."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from pllo.experiments import (
    METHOD_BY_NAME,
    WORKLOAD_METHODS,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
WORKLOAD_PROFILE_JSON = PROJECT_ROOT / "outputs" / "workload_profile.json"
WORKLOAD_PROFILE_MD = PROJECT_ROOT / "outputs" / "workload_profile.md"


METHOD_NAME = "ours_compatible_nonlinear_islands"


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------


def test_method_registered() -> None:
    """The new method must appear in the global registry and be flagged projected."""
    assert METHOD_NAME in METHOD_BY_NAME, list(METHOD_BY_NAME.keys())
    method = METHOD_BY_NAME[METHOD_NAME]
    assert method.implemented is False
    assert method.uses_compatible_nonlinear_islands is True
    assert method.uses_dense_sandwich is True
    assert method.uses_fresh_permutation is True
    assert method.online_extra_matmul_count == 0
    assert method.security_profile == "proxy-evaluated, not formal"


def test_existing_methods_have_default_extension_fields() -> None:
    """Existing methods get safe defaults for the new fields."""
    for method in WORKLOAD_METHODS:
        if method.name == METHOD_NAME:
            continue
        assert method.uses_compatible_nonlinear_islands is False
        assert method.online_extra_matmul_count == 0
        assert method.security_profile == "n/a"


# ---------------------------------------------------------------------------
# Profile JSON (regenerated by run_workload_profile.py)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def profile_payload() -> dict:
    if not WORKLOAD_PROFILE_JSON.exists():
        pytest.skip(
            "outputs/workload_profile.json missing — run "
            "`python scripts/run_workload_profile.py` first."
        )
    return json.loads(WORKLOAD_PROFILE_JSON.read_text(encoding="utf-8"))


def test_profile_contains_compatible_island_method(profile_payload) -> None:
    assert METHOD_NAME in profile_payload["methods"]


def test_profile_method_is_marked_projected(profile_payload) -> None:
    m = profile_payload["methods"][METHOD_NAME]
    assert m["implemented"] is False
    assert m["wall_time_source"] == "projected_from_op_counts"
    assert m["measured_wall_time_ms"] is None
    assert m["security_profile"] == "proxy-evaluated, not formal"


def test_profile_method_has_zero_online_extra_matmul(profile_payload) -> None:
    m = profile_payload["methods"][METHOD_NAME]
    assert m["online_extra_matmul_count"] == 0


def test_profile_method_has_boundary_formula(profile_payload) -> None:
    m = profile_payload["methods"][METHOD_NAME]
    formula = m["boundary_calls_formula"]
    assert isinstance(formula, str) and formula.strip()
    assert "L + 2" in formula


def test_profile_paper_metrics_include_reductions(profile_payload) -> None:
    pm = profile_payload["paper_metrics"].get(METHOD_NAME)
    assert pm is not None, "paper_metrics.ours_compatible_nonlinear_islands missing"
    assert "trusted_compute_reduction_vs_ours_current" in pm
    assert "boundary_call_reduction_vs_ours_current" in pm
    assert "preprocessing_cost_increase_vs_ours_current" in pm
    assert pm["online_extra_matmul_count"] == 0
    assert pm["projected_not_measured"] is True
    assert pm["security_proxy_available"] is True
    # Boundary calls must drop vs ours_current (4L+1 → L+2).
    assert pm["boundary_call_reduction_vs_ours_current"] > 0
    # Trusted compute should not rise (LN/GELU now on GPU).
    assert pm["trusted_compute_reduction_vs_ours_current"] >= 0


def test_profile_method_ordering_between_ours_current_and_ours_ideal(
    profile_payload,
) -> None:
    """ours_compatible_nonlinear_islands must sit between ours_current and ours_ideal."""
    ours_current = profile_payload["methods"]["ours_current"]
    ours_ideal = profile_payload["methods"]["ours_ideal_gpu_nonlinear"]
    islands = profile_payload["methods"][METHOD_NAME]

    # Boundary: ours_current > islands > ours_ideal
    assert ours_current["online_boundary_calls"] > islands["online_boundary_calls"]
    assert islands["online_boundary_calls"] > ours_ideal["online_boundary_calls"]
    # Trusted compute: ours_current > islands >= ours_ideal
    assert ours_current["online_trusted_compute_ops"] > islands["online_trusted_compute_ops"]
    assert islands["online_trusted_compute_ops"] >= ours_ideal["online_trusted_compute_ops"]
    # Preprocessing: islands > ours_current (extra affine fold + perm absorb).
    assert islands["preprocessing_trusted_ops"] > ours_current["preprocessing_trusted_ops"]


def test_profile_method_records_wrapper_integration_status(profile_payload) -> None:
    """Stage 5.3a / 5.3b / 5.3c — partial wrapper integration must be visible per-method."""
    m = profile_payload["methods"][METHOD_NAME]
    assert m.get("partial_implementation") is True
    # BERT / T5 are probe-level only — method must NOT be marked fully implemented.
    assert m["implemented"] is False
    assert m["wall_time_source"] == "projected_from_op_counts"
    assert m.get("measured_integration_scope") in (
        "cross_architecture_probe_level",
        "cross_architecture_plus_modern_decoder_probe_level",
        "cross_architecture_plus_modern_decoder_block_level",
        "cross_architecture_plus_modern_decoder_model_level",
    )
    assert m.get("all_architecture_probe_level_implemented") is True
    assert m.get("full_runtime_integrated") is False
    status = m.get("wrapper_integration_status")
    assert status is not None
    assert status["gpt2_single_block"] == "implemented"
    assert status["gpt2_model_level"] == "implemented"
    assert status["bert"] == "implemented_probe_level"
    assert status["t5"] == "implemented_probe_level"
    # Top-level summary mirrors the per-method status.
    top = profile_payload.get("wrapper_integration_status", {}).get(METHOD_NAME)
    assert top is not None
    assert top["gpt2_single_block"] == "implemented"
    assert top["gpt2_model_level"] == "implemented"
    assert top["bert"] == "implemented_probe_level"
    assert top["t5"] == "implemented_probe_level"
    assert top.get("full_runtime_integrated") is False
    assert top.get("all_architecture_probe_level_implemented") is True


def test_profile_method_preprocessing_breakdown_present(profile_payload) -> None:
    m = profile_payload["methods"][METHOD_NAME]
    pb = m.get("preprocessing_breakdown")
    assert pb is not None
    assert pb["affine_folding_ops"] > 0
    assert pb["permutation_absorption_ops"] > 0
    assert pb["compatible_mask_generation_ops"] > 0


def test_interaction_breakdown_includes_new_categories(profile_payload) -> None:
    ib = profile_payload["interaction_breakdown"]
    for category in (
        "preprocessing_affine_folding",
        "preprocessing_permutation_absorption",
        "compatible_norm_core_gpu",
        "compatible_activation_island_gpu",
        "dense_sandwich_transition",
        "security_proxy_requirements",
    ):
        assert category in ib, f"interaction_breakdown missing category {category}"
        # Each new category has a per-method record for every method.
        assert METHOD_NAME in ib[category]
    # ``security_proxy_requirements`` notes must reference the required
    # mitigations only for the compatible-island method.
    notes = ib["security_proxy_requirements"][METHOD_NAME]["notes"]
    assert "fresh permutation" in notes.lower()
    assert "dense" in notes.lower() and "sandwich" in notes.lower()


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def test_workload_profile_markdown_contains_required_phrases() -> None:
    if not WORKLOAD_PROFILE_MD.exists():
        pytest.skip("outputs/workload_profile.md missing — run the script first.")
    md = WORKLOAD_PROFILE_MD.read_text(encoding="utf-8")
    for section in (
        "Compatible Nonlinear Islands Method",
        "Boundary Call Formulas",
        "Trusted Compute Reduction",
        "Preprocessing Cost Increase",
        "Online Extra Matmul Count",
        "Security Proxy Caveats",
    ):
        assert section in md, f"missing section: {section}"
    for phrase in (
        "ours_compatible_nonlinear_islands is a projected method",
        "Stage 5.2a correctness probes",
        "Stage 5.2b security proxies",
        "not yet integrated into GPT-2 / BERT / T5 wrappers",
        "Compatible mask families are weaker than unrestricted dense masks",
        "Fresh permutation, dense sandwiching, and pad at Linear boundaries are required mitigations",
        "online_extra_matmul_count = 0",
        "not a real TEE measurement",
        # Stage 5.3a / 5.3b / 5.3c — cross-architecture probe-level integration.
        "Stage 5.3a Wrapper Integration Status",
        "GPT-2 model-level integration is available",
        "BERT/T5 are probe-level integrations, not full wrappers",
        # Stage 5.3c value or Stage 6.4-extended value.
        "full_runtime_integrated = False",
        "all_architecture_probe_level_implemented = True",
        "security_profile` remains `proxy-evaluated, not formal`",
    ):
        assert phrase in md, f"missing phrase: {phrase!r}"
    # measured_integration_scope must be present in one of the valid forms.
    assert any(
        phrase in md
        for phrase in (
            "measured_integration_scope = \"cross_architecture_probe_level\"",
            "measured_integration_scope = \"cross_architecture_plus_modern_decoder_probe_level\"",
            "measured_integration_scope = \"cross_architecture_plus_modern_decoder_block_level\"",
            "measured_integration_scope = \"cross_architecture_plus_modern_decoder_model_level\"",
        )
    )
