"""Stage 7.0 — tests for the LoRA training probe."""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

import pytest

from pllo.experiments.lora_training_probe import (
    LoRATrainingProbeConfig,
    VALID_OPTIMIZERS,
    normalize_optimizer,
    run_lora_training_probe,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = PROJECT_ROOT / "scripts" / "run_lora_training_experiments.py"


def _cfg(**overrides) -> LoRATrainingProbeConfig:
    base = dict(
        seed=2026, batch_size=4, d_in=16, d_out=8, rank=3,
        num_steps=3, lr=1e-2, optimizer="sgd",
        use_pad=True, fresh_u_per_step=True, fresh_masks_per_step=True,
        dtype="float64",
    )
    base.update(overrides)
    return LoRATrainingProbeConfig(**base)


# ---------------------------------------------------------------------------
# 1. run_lora_training_probe small config runs
# ---------------------------------------------------------------------------


def test_run_lora_training_probe_runs_under_small_config() -> None:
    report = run_lora_training_probe(_cfg())
    assert report["lora_private_training_status"] == "prototype"
    assert (
        report["training_step_correctness"]["num_steps"]
        == _cfg().num_steps
    )


# ---------------------------------------------------------------------------
# 2. loss_plain and loss_masked close
# ---------------------------------------------------------------------------


def test_loss_plain_and_loss_masked_close() -> None:
    report = run_lora_training_probe(_cfg())
    tc = report["training_step_correctness"]
    assert tc["allclose"] is True
    assert tc["max_loss_diff"] < 1e-9


# ---------------------------------------------------------------------------
# 3. grad_A / grad_B close
# ---------------------------------------------------------------------------


def test_gradients_match_between_plain_and_masked() -> None:
    report = run_lora_training_probe(_cfg())
    tc = report["training_step_correctness"]
    assert tc["max_grad_a_err"] < 1e-9
    assert tc["max_grad_b_err"] < 1e-9


# ---------------------------------------------------------------------------
# 4. adapter update close
# ---------------------------------------------------------------------------


def test_adapter_updates_match_between_plain_and_masked() -> None:
    report = run_lora_training_probe(_cfg())
    tc = report["training_step_correctness"]
    assert tc["final_adapter_a_update_err"] < 1e-9
    assert tc["final_adapter_b_update_err"] < 1e-9


# ---------------------------------------------------------------------------
# 5. use_pad=True works
# ---------------------------------------------------------------------------


def test_use_pad_path_remains_allclose() -> None:
    report = run_lora_training_probe(_cfg(use_pad=True))
    assert report["pad_compensation"]["use_pad"] is True
    assert report["training_step_correctness"]["allclose"] is True


# ---------------------------------------------------------------------------
# 6. fresh_u_per_step=True works
# ---------------------------------------------------------------------------


def test_fresh_u_per_step_path_remains_allclose() -> None:
    report = run_lora_training_probe(_cfg(fresh_u_per_step=True))
    assert report["config"]["fresh_u_per_step"] is True
    assert report["training_step_correctness"]["allclose"] is True


# ---------------------------------------------------------------------------
# 7. Markdown generated by runner script
# ---------------------------------------------------------------------------


def test_runner_script_generates_json_csv_md(tmp_path: Path) -> None:
    subprocess.run(
        [
            sys.executable, str(SCRIPT),
            "--output-dir", str(tmp_path),
            "--num-steps", "3",
            "--d-in", "16", "--d-out", "8", "--rank", "3",
            "--batch-size", "4",
        ],
        cwd=PROJECT_ROOT, capture_output=True, check=True, text=True,
    )
    md = (tmp_path / "lora_training_experiments.md").read_text(encoding="utf-8")
    for phrase in (
        "Experiment Scope",
        "LoRA Linear Masking Formula",
        "Forward Correctness",
        "Training-Step Correctness",
        "Gradient / Optimizer Handling",
        "Pad Compensation",
        "Limitations",
        "Next Stage Plan",
    ):
        assert phrase in md, f"missing markdown section: {phrase!r}"
    json_text = (tmp_path / "lora_training_experiments.json").read_text(
        encoding="utf-8"
    )
    # No raw tensor literals in JSON.
    assert "tensor(" not in json_text
    with (tmp_path / "lora_training_experiments.csv").open(
        encoding="utf-8"
    ) as f:
        rows = list(csv.DictReader(f))
    assert any(r["section"] == "summary" for r in rows)
    assert any(r["section"] == "per_step" for r in rows)


# ---------------------------------------------------------------------------
# 8. Markdown includes "backward remains trusted" limitation
# ---------------------------------------------------------------------------


def test_markdown_includes_trusted_backward_limitation(tmp_path: Path) -> None:
    subprocess.run(
        [
            sys.executable, str(SCRIPT),
            "--output-dir", str(tmp_path),
            "--num-steps", "2",
            "--d-in", "12", "--d-out", "8", "--rank", "2",
            "--batch-size", "3",
        ],
        cwd=PROJECT_ROOT, capture_output=True, check=True, text=True,
    )
    md = (tmp_path / "lora_training_experiments.md").read_text(encoding="utf-8")
    assert "training backward remains trusted" in md.lower()
    assert "stage 7.0 prototype" in md.lower()
    # Adapter never merged.
    assert "merge_adapter_into_w" in md
    # No PEFT integration claim.
    assert "no peft" in md.lower() or "peft" in md.lower()


# ---------------------------------------------------------------------------
# AdamW optimizer path
# ---------------------------------------------------------------------------


def test_adamw_optimizer_path_remains_allclose() -> None:
    report = run_lora_training_probe(_cfg(optimizer="adamw", lr=1e-3))
    tc = report["training_step_correctness"]
    assert tc["allclose"] is True
    assert tc["final_adapter_a_update_err"] < 1e-9


def test_normalize_optimizer_rejects_unknown() -> None:
    assert normalize_optimizer(None) == "sgd"
    assert "sgd" in VALID_OPTIMIZERS
    assert "adamw" in VALID_OPTIMIZERS
    with pytest.raises(ValueError):
        normalize_optimizer("adamax")


# ---------------------------------------------------------------------------
# Visibility / leakage contract
# ---------------------------------------------------------------------------


def test_gpu_does_not_see_raw_adapter_or_private_data() -> None:
    report = run_lora_training_probe(_cfg())
    gr = report["gradient_and_optimizer_handling"]
    vis = gr["gpu_visibility"]
    assert vis["raw_a"] is False
    assert vis["raw_b"] is False
    assert vis["raw_x"] is False
    assert vis["grad_a"] is False
    assert vis["grad_b"] is False
    assert vis["optimizer_state"] is False
    assert vis["private_target_y"] is False
    assert gr["merge_adapter_into_w"] is False


def test_json_safe_no_raw_tensors() -> None:
    report = run_lora_training_probe(_cfg())
    text = json.dumps(report, default=str)
    assert "tensor(" not in text
