"""Plain and obfuscated tensor operations."""

from pllo.ops.attention import (
    causal_self_attention_obfuscated,
    causal_self_attention_plain,
    generate_head_block_mask,
    generate_qk_mask_pair,
    make_causal_mask,
    qk_mask_constraint_error,
)
from pllo.ops.layernorm import layer_norm_plain, trusted_layer_norm
from pllo.ops.linear import linear_plain, linear_obfuscated
from pllo.ops.norm import (
    TrustedNormConfig,
    layer_norm_reference,
    rms_norm_reference,
    trusted_norm_forward,
)
from pllo.ops.compatible_masks import (
    apply_permutation_columns,
    center_matrix,
    centered_orthogonality_error,
    generate_dense_invertible,
    generate_mean_preserving_orthogonal,
    generate_orthogonal,
    generate_permutation,
    matrix_fingerprint,
    mean_preservation_error,
    orthogonal_error,
)
from pllo.ops.nonlinear_islands import (
    fold_layernorm_affine_into_linear,
    fold_rmsnorm_affine_into_linear,
    gelu_reference,
    layernorm_core,
    relu_reference,
    rmsnorm_core,
    run_activation_permutation_island,
    run_gelu_mlp_island,
    run_layernorm_mean_preserving_island,
    run_rmsnorm_orthogonal_island,
    run_swiglu_mlp_island,
    run_swiglu_paired_permutation_island,
    silu_reference,
    swiglu_reference,
)
from pllo.ops.lm_head import lm_head_obfuscated, lm_head_plain
from pllo.ops.lora_linear import lora_linear_plain, lora_linear_obfuscated
from pllo.ops.mlp import mlp_obfuscated, mlp_plain

__all__ = [
    "causal_self_attention_obfuscated",
    "causal_self_attention_plain",
    "generate_qk_mask_pair",
    "generate_head_block_mask",
    "layer_norm_plain",
    "linear_plain",
    "linear_obfuscated",
    "lm_head_obfuscated",
    "lm_head_plain",
    "lora_linear_plain",
    "lora_linear_obfuscated",
    "make_causal_mask",
    "mlp_obfuscated",
    "mlp_plain",
    "qk_mask_constraint_error",
    "trusted_layer_norm",
    "TrustedNormConfig",
    "layer_norm_reference",
    "rms_norm_reference",
    "trusted_norm_forward",
    "apply_permutation_columns",
    "center_matrix",
    "centered_orthogonality_error",
    "generate_dense_invertible",
    "generate_mean_preserving_orthogonal",
    "generate_orthogonal",
    "generate_permutation",
    "matrix_fingerprint",
    "mean_preservation_error",
    "orthogonal_error",
    "fold_layernorm_affine_into_linear",
    "fold_rmsnorm_affine_into_linear",
    "gelu_reference",
    "layernorm_core",
    "relu_reference",
    "rmsnorm_core",
    "run_activation_permutation_island",
    "run_gelu_mlp_island",
    "run_layernorm_mean_preserving_island",
    "run_rmsnorm_orthogonal_island",
    "run_swiglu_mlp_island",
    "run_swiglu_paired_permutation_island",
    "silu_reference",
    "swiglu_reference",
]
