"""Plain and obfuscated tensor operations."""

from pllo.ops.attention import (
    causal_self_attention_obfuscated,
    causal_self_attention_plain,
    generate_head_block_mask,
    generate_qk_mask_pair,
    make_causal_mask,
    qk_mask_constraint_error,
)
from pllo.ops.layernorm import layer_norm_plain, trusted_layer_norm
from pllo.ops.linear import linear_plain, linear_obfuscated
from pllo.ops.norm import (
    TrustedNormConfig,
    layer_norm_reference,
    rms_norm_reference,
    trusted_norm_forward,
)
from pllo.ops.compatible_masks import (
    apply_permutation_columns,
    center_matrix,
    centered_orthogonality_error,
    generate_dense_invertible,
    generate_mean_preserving_orthogonal,
    generate_orthogonal,
    generate_permutation,
    matrix_fingerprint,
    mean_preservation_error,
    orthogonal_error,
)
from pllo.ops.nonlinear_islands import (
    fold_layernorm_affine_into_linear,
    fold_rmsnorm_affine_into_linear,
    gelu_reference,
    layernorm_core,
    relu_reference,
    rmsnorm_core,
    run_activation_permutation_island,
    run_gelu_mlp_island,
    run_layernorm_mean_preserving_island,
    run_rmsnorm_orthogonal_island,
    run_swiglu_mlp_island,
    run_swiglu_paired_permutation_island,
    silu_reference,
    swiglu_reference,
)
from pllo.ops.lm_head import lm_head_obfuscated, lm_head_plain
from pllo.ops.lora_linear import lora_linear_plain, lora_linear_obfuscated
from pllo.ops.lora import (
    LoRAConfig,
    LoRAState,
    MaskedLoRAForwardConfig,
    create_masked_lora_state,
    init_lora_adapters,
    lora_state_fingerprint,
    make_lora_pad_compensation,
    masked_lora_linear_forward,
    obfuscate_lora_input,
    plain_lora_linear_forward,
    recover_masked_output,
    run_masked_lora_linear,
    transform_linear_weight_lora,
    transform_lora_adapter,
)
from pllo.ops.lora_backward import (
    MaskedLoRABackwardConfig,
    invert_upstream_gradient_mask,
    make_lora_grad_pad_compensation,
    masked_lora_backward,
    plain_lora_backward_reference,
    recover_lora_gradients,
    run_masked_lora_backward,
    transform_upstream_gradient,
)
from pllo.ops.lora_rank_padding import (
    RankPaddingConfig,
    VALID_DUMMY_STRATEGIES,
    create_rank_padded_lora_adapters,
    dummy_contribution_norm,
    extract_real_gradients,
    plain_rank_padded_lora_backward_reference,
    plain_rank_padded_lora_forward,
    run_masked_rank_padded_lora_backward,
    run_masked_rank_padded_lora_linear,
    validate_rank_padding_config,
    visible_shape_fingerprint,
)
from pllo.ops.mlp import mlp_obfuscated, mlp_plain

__all__ = [
    "causal_self_attention_obfuscated",
    "causal_self_attention_plain",
    "generate_qk_mask_pair",
    "generate_head_block_mask",
    "layer_norm_plain",
    "linear_plain",
    "linear_obfuscated",
    "lm_head_obfuscated",
    "lm_head_plain",
    "lora_linear_plain",
    "lora_linear_obfuscated",
    "make_causal_mask",
    "mlp_obfuscated",
    "mlp_plain",
    "qk_mask_constraint_error",
    "trusted_layer_norm",
    "TrustedNormConfig",
    "layer_norm_reference",
    "rms_norm_reference",
    "trusted_norm_forward",
    "apply_permutation_columns",
    "center_matrix",
    "centered_orthogonality_error",
    "generate_dense_invertible",
    "generate_mean_preserving_orthogonal",
    "generate_orthogonal",
    "generate_permutation",
    "matrix_fingerprint",
    "mean_preservation_error",
    "orthogonal_error",
    "fold_layernorm_affine_into_linear",
    "fold_rmsnorm_affine_into_linear",
    "gelu_reference",
    "layernorm_core",
    "relu_reference",
    "rmsnorm_core",
    "run_activation_permutation_island",
    "run_gelu_mlp_island",
    "run_layernorm_mean_preserving_island",
    "run_rmsnorm_orthogonal_island",
    "run_swiglu_mlp_island",
    "run_swiglu_paired_permutation_island",
    "silu_reference",
    "swiglu_reference",
    "LoRAConfig",
    "LoRAState",
    "MaskedLoRAForwardConfig",
    "create_masked_lora_state",
    "init_lora_adapters",
    "lora_state_fingerprint",
    "make_lora_pad_compensation",
    "masked_lora_linear_forward",
    "obfuscate_lora_input",
    "plain_lora_linear_forward",
    "recover_masked_output",
    "run_masked_lora_linear",
    "transform_linear_weight_lora",
    "transform_lora_adapter",
    "MaskedLoRABackwardConfig",
    "invert_upstream_gradient_mask",
    "make_lora_grad_pad_compensation",
    "masked_lora_backward",
    "plain_lora_backward_reference",
    "recover_lora_gradients",
    "run_masked_lora_backward",
    "transform_upstream_gradient",
    "RankPaddingConfig",
    "VALID_DUMMY_STRATEGIES",
    "create_rank_padded_lora_adapters",
    "dummy_contribution_norm",
    "extract_real_gradients",
    "plain_rank_padded_lora_backward_reference",
    "plain_rank_padded_lora_forward",
    "run_masked_rank_padded_lora_backward",
    "run_masked_rank_padded_lora_linear",
    "validate_rank_padding_config",
    "visible_shape_fingerprint",
]
