"""Generate the reproducibility appendix (Markdown + LaTeX + JSON).

Collects reproducibility metadata from result JSONs and explicit CLI args and
renders ``docs/paper_draft/reproducibility_appendix.md`` plus a LaTeX table of
the key hashes. All inputs are optional and the renderer is robust to missing
data (renders ``(not provided)``).

Software versions are auto-collected (python + best-effort torch/transformers)
WITHOUT importing torch -- via ``importlib.metadata.version`` in try/except.

stdlib only (json / hashlib / pathlib / importlib.metadata). main() -> int.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from pllo.experiments.nonlinear_designs import (  # noqa: E402
    add_nonlinear_backend_arg,
    nonlinear_design_report_fields,
    normalize_nonlinear_backend,
)

STAGE = "reproducibility_appendix"
NOT_PROVIDED = "(not provided)"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def load_json(path: Path) -> Any:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _g(d: Any, *keys: str, default: Any = None) -> Any:
    """Nested getter; returns the first key found at the top level, else
    searches one level into nested dicts. Returns ``default`` if absent."""
    if not isinstance(d, dict):
        return default
    for k in keys:
        if k in d and d[k] is not None:
            return d[k]
    # one-level descent
    for v in d.values():
        if isinstance(v, dict):
            for k in keys:
                if k in v and v[k] is not None:
                    return v[k]
    return default


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def best_effort_versions() -> Dict[str, Optional[str]]:
    """Python + best-effort package versions WITHOUT importing the packages."""
    versions: Dict[str, Optional[str]] = {
        "python": platform.python_version(),
        "platform": platform.platform(),
    }
    try:
        from importlib import metadata as importlib_metadata  # py3.8+
    except Exception:  # pragma: no cover
        importlib_metadata = None  # type: ignore
    for pkg in ("torch", "transformers", "numpy"):
        ver: Optional[str] = None
        if importlib_metadata is not None:
            try:
                ver = importlib_metadata.version(pkg)
            except Exception:
                ver = None
        versions[pkg] = ver
    return versions


def collect_from_results(result_jsons: List[Path]) -> Dict[str, Any]:
    """Pull reproducibility-relevant fields out of result JSONs."""
    collected: Dict[str, Any] = {
        "model_name": None,
        "model_path": None,
        "manifest_hash": None,
        "nonlinear_backend": None,
        "runtime_hash": None,
        "mr_td": None,
        "evidence_report_data": None,
        "folded_package_path": None,
        "source_files": [],
    }
    for p in result_jsons:
        try:
            data = load_json(p)
        except Exception:
            continue
        collected["source_files"].append(str(p))
        for key, aliases in (
            ("model_name", ("model_name",)),
            ("model_path", ("model_path",)),
            ("manifest_hash", ("manifest_hash", "base_manifest_hash")),
            ("nonlinear_backend", ("nonlinear_backend",)),
            ("runtime_hash", ("runtime_hash",)),
            ("mr_td", ("mr_td",)),
            ("evidence_report_data",
             ("evidence_report_data", "attestation_report_data", "report_data")),
            ("folded_package_path", ("folded_package_path",)),
        ):
            if collected[key] is None:
                val = _g(data, *aliases)
                if val is not None:
                    collected[key] = val
    return collected


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------


def _v(x: Any) -> str:
    if x is None or x == "":
        return NOT_PROVIDED
    return str(x)


def render_markdown(report: Dict[str, Any]) -> str:
    L: List[str] = []
    L.append("# Reproducibility appendix")
    L.append("")
    L.append("Auto-generated by `scripts/render_reproducibility_appendix.py`. "
             "Fields shown as `(not provided)` were not supplied.")
    L.append("")

    L.append("## Hardware")
    L.append("")
    L.append(_v(report.get("hardware")))
    L.append("")

    L.append("## Software versions")
    L.append("")
    sv = report.get("software_versions") or {}
    if sv:
        L.append("| package | version |")
        L.append("|---|---|")
        for k in sorted(sv):
            L.append("| %s | %s |" % (k, _v(sv[k])))
    else:
        L.append(NOT_PROVIDED)
    L.append("")

    L.append("## Model")
    L.append("")
    model = report.get("model") or {}
    L.append("- name: %s" % _v(model.get("name")))
    L.append("- path: %s" % _v(model.get("path")))
    L.append("- hash: %s" % _v(model.get("hash")))
    L.append("")

    L.append("## Artifacts and hashes")
    L.append("")
    L.append("- folded_package_manifest_hash: %s"
             % _v(report.get("folded_package_manifest_hash")))
    L.append("- embedding_artifact_hash: %s"
             % _v(report.get("embedding_artifact_hash")))
    L.append("- folded_lora_package_hash: %s"
             % _v(report.get("folded_lora_package_hash")))
    L.append("")
    art = report.get("output_artifact_hashes") or {}
    if art:
        L.append("| artifact | sha256 |")
        L.append("|---|---|")
        for path in sorted(art):
            L.append("| %s | %s |" % (path, art[path]))
    else:
        L.append("output artifacts: %s" % NOT_PROVIDED)
    L.append("")

    L.append("## Attestation")
    L.append("")
    L.append("- runtime_hash: %s" % _v(report.get("runtime_hash")))
    L.append("- mr_td: %s" % _v(report.get("mr_td")))
    L.append("- attestation_report_data: %s"
             % _v(report.get("attestation_report_data")))
    L.append("")

    L.append("## Datasets")
    L.append("")
    cards = report.get("dataset_cards") or []
    if cards:
        for c in cards:
            name = c.get("name") if isinstance(c, dict) else None
            L.append("- %s" % _v(name if name else json.dumps(c, default=str)))
    else:
        L.append(NOT_PROVIDED)
    L.append("")

    L.append("## Nonlinear design")
    L.append("")
    nb = report.get("nonlinear_backend")
    if nb:
        L.append("- nonlinear_backend: %s" % nb)
        L.append("- nonlinear_design_label: %s"
                 % _v(report.get("nonlinear_design_label")))
        L.append("- nonlinear_design_metadata_hash: %s"
                 % _v(report.get("nonlinear_design_metadata_hash")))
    else:
        L.append(NOT_PROVIDED)
    L.append("")

    L.append("## Commands")
    L.append("")
    cmds = report.get("commands") or []
    if cmds:
        L.append("```sh")
        for c in cmds:
            L.append(str(c))
        L.append("```")
    else:
        L.append(NOT_PROVIDED)
    L.append("")

    return "\n".join(L) + "\n"


def _tex_escape(text: str) -> str:
    repl = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
            "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}",
            "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
    return "".join(repl.get(ch, ch) for ch in text)


def render_latex(report: Dict[str, Any]) -> str:
    model = report.get("model") or {}
    pairs = [
        ("model name", model.get("name")),
        ("model hash", model.get("hash")),
        ("folded package manifest hash",
         report.get("folded_package_manifest_hash")),
        ("embedding artifact hash", report.get("embedding_artifact_hash")),
        ("folded LoRA package hash", report.get("folded_lora_package_hash")),
        ("runtime hash", report.get("runtime_hash")),
        ("mr_td", report.get("mr_td")),
        ("attestation report data", report.get("attestation_report_data")),
        ("nonlinear design metadata hash",
         report.get("nonlinear_design_metadata_hash")),
    ]
    lines = ["\\begin{tabular}{ll}", "\\hline",
             "key & value \\\\", "\\hline"]
    for k, v in pairs:
        val = v if v is not None else "--"
        lines.append("%s & %s \\\\" % (_tex_escape(k), _tex_escape(str(val))))
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _write(path: Optional[str], content: str) -> None:
    if not path:
        return
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--result-json", action="append", default=[],
                   help="result JSON to scrape (repeatable).")
    p.add_argument("--hardware", default=None, help="free-text hardware desc.")
    p.add_argument("--software-versions-json", default=None,
                   help="JSON of {package: version}; auto-collected if absent.")
    p.add_argument("--model-name", default=None)
    p.add_argument("--model-path", default=None)
    p.add_argument("--model-hash", default=None)
    p.add_argument("--folded-package-manifest-hash", default=None)
    p.add_argument("--embedding-artifact-hash", default=None)
    p.add_argument("--folded-lora-package-hash", default=None)
    p.add_argument("--dataset-card-json", action="append", default=[],
                   help="dataset card JSON (repeatable).")
    p.add_argument("--runtime-hash", default=None)
    p.add_argument("--mr-td", default=None)
    p.add_argument("--attestation-report-data", default=None)
    p.add_argument("--commands-file", default=None,
                   help="file with shell commands (one per line).")
    p.add_argument("--output-artifact", action="append", default=[],
                   help="artifact file path -> sha256 (repeatable).")
    add_nonlinear_backend_arg(p, required=False, default=None)
    p.add_argument("--output-md",
                   default=str(REPO_ROOT / "docs" / "paper_draft"
                               / "reproducibility_appendix.md"))
    p.add_argument("--output-tex", default=None)
    p.add_argument("--output-json", default=None)
    return p


def build_report(args: argparse.Namespace) -> Dict[str, Any]:
    scraped = collect_from_results([Path(p) for p in args.result_json])

    # software versions
    if args.software_versions_json:
        try:
            software_versions = load_json(Path(args.software_versions_json))
        except Exception:
            software_versions = best_effort_versions()
    else:
        software_versions = best_effort_versions()

    # dataset cards
    dataset_cards: List[Any] = []
    for cp in args.dataset_card_json:
        try:
            dataset_cards.append(load_json(Path(cp)))
        except Exception:
            dataset_cards.append({"path": str(cp), "error": "load_failed"})

    # commands
    commands: List[str] = []
    if args.commands_file:
        try:
            for line in Path(args.commands_file).read_text(
                    encoding="utf-8").splitlines():
                if line.strip():
                    commands.append(line.rstrip("\n"))
        except Exception:
            pass

    # output artifact hashes
    artifact_hashes: Dict[str, str] = {}
    for ap in args.output_artifact:
        try:
            artifact_hashes[str(ap)] = sha256_file(Path(ap))
        except Exception:
            artifact_hashes[str(ap)] = "ERROR_unreadable"

    def pick(cli_val: Any, scraped_key: str) -> Any:
        if cli_val is not None:
            return cli_val
        return scraped.get(scraped_key)

    report: Dict[str, Any] = {
        "stage": STAGE,
        "hardware": args.hardware,
        "software_versions": software_versions,
        "model": {
            "name": pick(args.model_name, "model_name"),
            "path": pick(args.model_path, "model_path"),
            "hash": args.model_hash,
        },
        "folded_package_manifest_hash": pick(
            args.folded_package_manifest_hash, "manifest_hash"),
        "embedding_artifact_hash": args.embedding_artifact_hash,
        "folded_lora_package_hash": args.folded_lora_package_hash,
        "dataset_cards": dataset_cards,
        "runtime_hash": pick(args.runtime_hash, "runtime_hash"),
        "mr_td": pick(args.mr_td, "mr_td"),
        "attestation_report_data": pick(
            args.attestation_report_data, "evidence_report_data"),
        "commands": commands,
        "output_artifact_hashes": artifact_hashes,
        "scraped_result_files": scraped.get("source_files", []),
    }

    nb = getattr(args, "nonlinear_backend", None) or scraped.get(
        "nonlinear_backend")
    if nb:
        canon = normalize_nonlinear_backend(nb)
        report["nonlinear_backend"] = canon
        report.update(nonlinear_design_report_fields(canon))

    return report


def main() -> int:
    args = build_parser().parse_args()
    report = build_report(args)

    _write(args.output_md, render_markdown(report))
    _write(args.output_tex, render_latex(report))
    _write(args.output_json, json.dumps(report, indent=2, default=str))

    print("reproducibility_appendix: wrote %s" % args.output_md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
